/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { CreateOrderRequestDTO } from '../models';
// @ts-ignore
import { OrderSchemaDTO } from '../models';
// @ts-ignore
import { ReviewOrderRequestDTO } from '../models';
// @ts-ignore
import { ReviewedOrderResponseDTO } from '../models';
/**
 * OrderApi - axios parameter creator
 * @export
 */
export const OrderApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a order
         * @param {CreateOrderRequestDTO} createOrderRequestDTO 
         * @param {CreateOrderXLangEnum} [xLang] The language of the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrder: async (createOrderRequestDTO: CreateOrderRequestDTO, xLang?: CreateOrderXLangEnum, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createOrderRequestDTO' is not null or undefined
            assertParamExists('createOrder', 'createOrderRequestDTO', createOrderRequestDTO)
            const localVarPath = `/order`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xLang != null) {
                localVarHeaderParameter['x-lang'] = String(xLang);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createOrderRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all order\'s user
         * @param {GetAllUserOrdersXLangEnum} [xLang] The language of the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUserOrders: async (xLang?: GetAllUserOrdersXLangEnum, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/order`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xLang != null) {
                localVarHeaderParameter['x-lang'] = String(xLang);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Review a order
         * @param {ReviewOrderRequestDTO} reviewOrderRequestDTO 
         * @param {ReviewOrderXLangEnum} [xLang] The language of the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewOrder: async (reviewOrderRequestDTO: ReviewOrderRequestDTO, xLang?: ReviewOrderXLangEnum, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reviewOrderRequestDTO' is not null or undefined
            assertParamExists('reviewOrder', 'reviewOrderRequestDTO', reviewOrderRequestDTO)
            const localVarPath = `/order/review`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xLang != null) {
                localVarHeaderParameter['x-lang'] = String(xLang);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reviewOrderRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrderApi - functional programming interface
 * @export
 */
export const OrderApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrderApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a order
         * @param {CreateOrderRequestDTO} createOrderRequestDTO 
         * @param {CreateOrderXLangEnum} [xLang] The language of the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrder(createOrderRequestDTO: CreateOrderRequestDTO, xLang?: CreateOrderXLangEnum, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrderSchemaDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrder(createOrderRequestDTO, xLang, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrderApi.createOrder']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get all order\'s user
         * @param {GetAllUserOrdersXLangEnum} [xLang] The language of the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllUserOrders(xLang?: GetAllUserOrdersXLangEnum, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<OrderSchemaDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllUserOrders(xLang, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrderApi.getAllUserOrders']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Review a order
         * @param {ReviewOrderRequestDTO} reviewOrderRequestDTO 
         * @param {ReviewOrderXLangEnum} [xLang] The language of the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewOrder(reviewOrderRequestDTO: ReviewOrderRequestDTO, xLang?: ReviewOrderXLangEnum, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReviewedOrderResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewOrder(reviewOrderRequestDTO, xLang, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrderApi.reviewOrder']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * OrderApi - factory interface
 * @export
 */
export const OrderApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrderApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a order
         * @param {OrderApiCreateOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrder(requestParameters: OrderApiCreateOrderRequest, options?: AxiosRequestConfig): AxiosPromise<OrderSchemaDTO> {
            return localVarFp.createOrder(requestParameters.createOrderRequestDTO, requestParameters.xLang, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all order\'s user
         * @param {OrderApiGetAllUserOrdersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUserOrders(requestParameters: OrderApiGetAllUserOrdersRequest = {}, options?: AxiosRequestConfig): AxiosPromise<Array<OrderSchemaDTO>> {
            return localVarFp.getAllUserOrders(requestParameters.xLang, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Review a order
         * @param {OrderApiReviewOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewOrder(requestParameters: OrderApiReviewOrderRequest, options?: AxiosRequestConfig): AxiosPromise<ReviewedOrderResponseDTO> {
            return localVarFp.reviewOrder(requestParameters.reviewOrderRequestDTO, requestParameters.xLang, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createOrder operation in OrderApi.
 * @export
 * @interface OrderApiCreateOrderRequest
 */
export interface OrderApiCreateOrderRequest {
    /**
     * 
     * @type {CreateOrderRequestDTO}
     * @memberof OrderApiCreateOrder
     */
    readonly createOrderRequestDTO: CreateOrderRequestDTO

    /**
     * The language of the response
     * @type {'en' | 'vi_VN'}
     * @memberof OrderApiCreateOrder
     */
    readonly xLang?: CreateOrderXLangEnum
}

/**
 * Request parameters for getAllUserOrders operation in OrderApi.
 * @export
 * @interface OrderApiGetAllUserOrdersRequest
 */
export interface OrderApiGetAllUserOrdersRequest {
    /**
     * The language of the response
     * @type {'en' | 'vi_VN'}
     * @memberof OrderApiGetAllUserOrders
     */
    readonly xLang?: GetAllUserOrdersXLangEnum
}

/**
 * Request parameters for reviewOrder operation in OrderApi.
 * @export
 * @interface OrderApiReviewOrderRequest
 */
export interface OrderApiReviewOrderRequest {
    /**
     * 
     * @type {ReviewOrderRequestDTO}
     * @memberof OrderApiReviewOrder
     */
    readonly reviewOrderRequestDTO: ReviewOrderRequestDTO

    /**
     * The language of the response
     * @type {'en' | 'vi_VN'}
     * @memberof OrderApiReviewOrder
     */
    readonly xLang?: ReviewOrderXLangEnum
}

/**
 * OrderApi - object-oriented interface
 * @export
 * @class OrderApi
 * @extends {BaseAPI}
 */
export class OrderApi extends BaseAPI {
    /**
     * 
     * @summary Create a order
     * @param {OrderApiCreateOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderApi
     */
    public createOrder(requestParameters: OrderApiCreateOrderRequest, options?: AxiosRequestConfig) {
        return OrderApiFp(this.configuration).createOrder(requestParameters.createOrderRequestDTO, requestParameters.xLang, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all order\'s user
     * @param {OrderApiGetAllUserOrdersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderApi
     */
    public getAllUserOrders(requestParameters: OrderApiGetAllUserOrdersRequest = {}, options?: AxiosRequestConfig) {
        return OrderApiFp(this.configuration).getAllUserOrders(requestParameters.xLang, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Review a order
     * @param {OrderApiReviewOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrderApi
     */
    public reviewOrder(requestParameters: OrderApiReviewOrderRequest, options?: AxiosRequestConfig) {
        return OrderApiFp(this.configuration).reviewOrder(requestParameters.reviewOrderRequestDTO, requestParameters.xLang, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
  * @export
  * @enum {string}
  */
export enum CreateOrderXLangEnum {
    En = 'en',
    ViVn = 'vi_VN'
}
/**
  * @export
  * @enum {string}
  */
export enum GetAllUserOrdersXLangEnum {
    En = 'en',
    ViVn = 'vi_VN'
}
/**
  * @export
  * @enum {string}
  */
export enum ReviewOrderXLangEnum {
    En = 'en',
    ViVn = 'vi_VN'
}
