/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { GetStatsResponseDTO } from '../models';
/**
 * StatsApi - axios parameter creator
 * @export
 */
export const StatsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get stats in a period of time
         * @param {string} fromDate From date to calculate revenue
         * @param {string} [toDate] To date to calculate revenue, default is today
         * @param {GetStatsSplitByEnum} [splitBy] Split by day, month or year
         * @param {boolean} [refreshCache] Trigger refresh cache to recalculate revenue data
         * @param {GetStatsXLangEnum} [xLang] The language of the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStats: async (fromDate: string, toDate?: string, splitBy?: GetStatsSplitByEnum, refreshCache?: boolean, xLang?: GetStatsXLangEnum, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fromDate' is not null or undefined
            assertParamExists('getStats', 'fromDate', fromDate)
            const localVarPath = `/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (fromDate !== undefined) {
                localVarQueryParameter['fromDate'] = (fromDate as any instanceof Date) ?
                    (fromDate as any).toISOString() :
                    fromDate;
            }

            if (toDate !== undefined) {
                localVarQueryParameter['toDate'] = (toDate as any instanceof Date) ?
                    (toDate as any).toISOString() :
                    toDate;
            }

            if (splitBy !== undefined) {
                localVarQueryParameter['splitBy'] = splitBy;
            }

            if (refreshCache !== undefined) {
                localVarQueryParameter['refreshCache'] = refreshCache;
            }

            if (xLang != null) {
                localVarHeaderParameter['x-lang'] = String(xLang);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StatsApi - functional programming interface
 * @export
 */
export const StatsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StatsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get stats in a period of time
         * @param {string} fromDate From date to calculate revenue
         * @param {string} [toDate] To date to calculate revenue, default is today
         * @param {GetStatsSplitByEnum} [splitBy] Split by day, month or year
         * @param {boolean} [refreshCache] Trigger refresh cache to recalculate revenue data
         * @param {GetStatsXLangEnum} [xLang] The language of the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStats(fromDate: string, toDate?: string, splitBy?: GetStatsSplitByEnum, refreshCache?: boolean, xLang?: GetStatsXLangEnum, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetStatsResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStats(fromDate, toDate, splitBy, refreshCache, xLang, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['StatsApi.getStats']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * StatsApi - factory interface
 * @export
 */
export const StatsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StatsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get stats in a period of time
         * @param {StatsApiGetStatsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStats(requestParameters: StatsApiGetStatsRequest, options?: AxiosRequestConfig): AxiosPromise<GetStatsResponseDTO> {
            return localVarFp.getStats(requestParameters.fromDate, requestParameters.toDate, requestParameters.splitBy, requestParameters.refreshCache, requestParameters.xLang, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getStats operation in StatsApi.
 * @export
 * @interface StatsApiGetStatsRequest
 */
export interface StatsApiGetStatsRequest {
    /**
     * From date to calculate revenue
     * @type {string}
     * @memberof StatsApiGetStats
     */
    readonly fromDate: string

    /**
     * To date to calculate revenue, default is today
     * @type {string}
     * @memberof StatsApiGetStats
     */
    readonly toDate?: string

    /**
     * Split by day, month or year
     * @type {'day' | 'week' | 'month' | 'year'}
     * @memberof StatsApiGetStats
     */
    readonly splitBy?: GetStatsSplitByEnum

    /**
     * Trigger refresh cache to recalculate revenue data
     * @type {boolean}
     * @memberof StatsApiGetStats
     */
    readonly refreshCache?: boolean

    /**
     * The language of the response
     * @type {'en' | 'vi_VN'}
     * @memberof StatsApiGetStats
     */
    readonly xLang?: GetStatsXLangEnum
}

/**
 * StatsApi - object-oriented interface
 * @export
 * @class StatsApi
 * @extends {BaseAPI}
 */
export class StatsApi extends BaseAPI {
    /**
     * 
     * @summary Get stats in a period of time
     * @param {StatsApiGetStatsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatsApi
     */
    public getStats(requestParameters: StatsApiGetStatsRequest, options?: AxiosRequestConfig) {
        return StatsApiFp(this.configuration).getStats(requestParameters.fromDate, requestParameters.toDate, requestParameters.splitBy, requestParameters.refreshCache, requestParameters.xLang, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
  * @export
  * @enum {string}
  */
export enum GetStatsSplitByEnum {
    Day = 'day',
    Week = 'week',
    Month = 'month',
    Year = 'year'
}
/**
  * @export
  * @enum {string}
  */
export enum GetStatsXLangEnum {
    En = 'en',
    ViVn = 'vi_VN'
}
