/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddCartRequestDTO
 */
export interface AddCartRequestDTO {
    /**
     * Product ID
     * @type {string}
     * @memberof AddCartRequestDTO
     */
    'productId': string;
    /**
     * sku of product\'s variation
     * @type {string}
     * @memberof AddCartRequestDTO
     */
    'sku': string;
    /**
     * Quantity of product, can be a negative to reduce quantity or remove product from cart
     * @type {number}
     * @memberof AddCartRequestDTO
     */
    'quantity': number;
}

