/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DistrictSchemaDTO } from './district-schema-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ProvinceSchemaDTO } from './province-schema-dto';
// May contain unused imports in some cases
// @ts-ignore
import { WardSchemaDTO } from './ward-schema-dto';

/**
 * 
 * @export
 * @interface AddressSchemaDTO
 */
export interface AddressSchemaDTO {
    /**
     * The name of address
     * @type {string}
     * @memberof AddressSchemaDTO
     */
    'addressName': string;
    /**
     * The name of customer
     * @type {string}
     * @memberof AddressSchemaDTO
     */
    'customerName'?: string;
    /**
     * The phone number of customer
     * @type {string}
     * @memberof AddressSchemaDTO
     */
    'phoneNumbers': string;
    /**
     * 
     * @type {ProvinceSchemaDTO}
     * @memberof AddressSchemaDTO
     */
    'provinceLevel': ProvinceSchemaDTO;
    /**
     * 
     * @type {DistrictSchemaDTO}
     * @memberof AddressSchemaDTO
     */
    'districtLevel': DistrictSchemaDTO;
    /**
     * 
     * @type {WardSchemaDTO}
     * @memberof AddressSchemaDTO
     */
    'wardLevel': WardSchemaDTO;
    /**
     * The detailed address
     * @type {string}
     * @memberof AddressSchemaDTO
     */
    'detail': string;
    /**
     * The boolean value to check if this address is default or not
     * @type {boolean}
     * @memberof AddressSchemaDTO
     */
    'isDefault'?: boolean;
}

