/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AttributeDTO
 */
export interface AttributeDTO {
    /**
     * Attribute id
     * @type {string}
     * @memberof AttributeDTO
     */
    '_id': string;
    /**
     * Attribute name
     * @type {string}
     * @memberof AttributeDTO
     */
    'name': string;
    /**
     * Attribute label
     * @type {string}
     * @memberof AttributeDTO
     */
    'label': string;
    /**
     * Attribute description
     * @type {string}
     * @memberof AttributeDTO
     */
    'description': string;
}

