/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlockActivitySchemaDTO
 */
export interface BlockActivitySchemaDTO {
    /**
     * The user who performed the activity
     * @type {string}
     * @memberof BlockActivitySchemaDTO
     */
    'activityBy': string;
    /**
     * The date and time of the activity
     * @type {string}
     * @memberof BlockActivitySchemaDTO
     */
    'activityAt': string;
    /**
     * The reason for the activity
     * @type {string}
     * @memberof BlockActivitySchemaDTO
     */
    'activityReason': string;
    /**
     * Additional notes about the activity
     * @type {string}
     * @memberof BlockActivitySchemaDTO
     */
    'activityNote': string;
    /**
     * The IP address of the user when the activity was performed
     * @type {string}
     * @memberof BlockActivitySchemaDTO
     */
    'activityIp': string;
}

