/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProductCartSchemaDTO } from './product-cart-schema-dto';

/**
 * 
 * @export
 * @interface CartDTO
 */
export interface CartDTO {
    /**
     * Cart ID
     * @type {string}
     * @memberof CartDTO
     */
    '_id': string;
    /**
     * User ID
     * @type {string}
     * @memberof CartDTO
     */
    'userId': string;
    /**
     * List of products in cart
     * @type {Array<ProductCartSchemaDTO>}
     * @memberof CartDTO
     */
    'products'?: Array<ProductCartSchemaDTO>;
    /**
     * Number of products in cart
     * @type {number}
     * @memberof CartDTO
     */
    'cartCountProducts': number;
    /**
     * Cart state
     * @type {string}
     * @memberof CartDTO
     */
    'cartState': CartDTOCartStateEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CartDTOCartStateEnum {
    Active = 'active',
    Inactive = 'inactive',
    Failed = 'failed',
    Pending = 'pending',
    Completed = 'completed'
}


