/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttributeDTO } from './attribute-dto';

/**
 * 
 * @export
 * @interface CategoryDTO
 */
export interface CategoryDTO {
    /**
     * Category id
     * @type {string}
     * @memberof CategoryDTO
     */
    '_id': string;
    /**
     * Category name
     * @type {string}
     * @memberof CategoryDTO
     */
    'name': string;
    /**
     * Category label
     * @type {string}
     * @memberof CategoryDTO
     */
    'label': string;
    /**
     * List of attributes
     * @type {Array<AttributeDTO>}
     * @memberof CategoryDTO
     */
    'requireAttributes': Array<AttributeDTO>;
    /**
     * Category description
     * @type {string}
     * @memberof CategoryDTO
     */
    'description': string;
    /**
     * Category image url
     * @type {string}
     * @memberof CategoryDTO
     */
    'url'?: string;
}

