/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChangePasswordRequestDTO
 */
export interface ChangePasswordRequestDTO {
    /**
     * Old password
     * @type {string}
     * @memberof ChangePasswordRequestDTO
     */
    'oldPassword': string;
    /**
     * New password to change
     * @type {string}
     * @memberof ChangePasswordRequestDTO
     */
    'newPassword': string;
    /**
     * Re-new password to change, must be same with `newPassword`
     * @type {string}
     * @memberof ChangePasswordRequestDTO
     */
    'reNewPassword': string;
}

