/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateKpiRequestDTO
 */
export interface CreateKpiRequestDTO {
    /**
     * KPI name
     * @type {string}
     * @memberof CreateKpiRequestDTO
     */
    'name': string;
    /**
     * KPI type
     * @type {string}
     * @memberof CreateKpiRequestDTO
     */
    'kpiType': CreateKpiRequestDTOKpiTypeEnum;
    /**
     * KPI value
     * @type {number}
     * @memberof CreateKpiRequestDTO
     */
    'value': number;
    /**
     * KPI start date
     * @type {string}
     * @memberof CreateKpiRequestDTO
     */
    'startDate': string;
    /**
     * KPI end date
     * @type {string}
     * @memberof CreateKpiRequestDTO
     */
    'endDate': string;
    /**
     * KPI status
     * @type {string}
     * @memberof CreateKpiRequestDTO
     */
    'kpiStatus'?: CreateKpiRequestDTOKpiStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateKpiRequestDTOKpiTypeEnum {
    Revenue = 'revenue',
    OrderComplete = 'order_complete'
}
/**
    * @export
    * @enum {string}
    */
export enum CreateKpiRequestDTOKpiStatusEnum {
    Active = 'active',
    Inactive = 'inactive'
}


