/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUserRequestDto
 */
export interface CreateUserRequestDto {
    /**
     * Username of user
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'userName': string;
    /**
     * Password of user
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'password': string;
    /**
     * Role of user
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'role'?: string;
    /**
     * Email of user
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'email'?: string;
    /**
     * First name of user
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'firstName'?: string;
    /**
     * Last name of user
     * @type {string}
     * @memberof CreateUserRequestDto
     */
    'lastName'?: string;
}

