/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateAttributeRequestDTO
 */
export interface CreateAttributeRequestDTO {
    /**
     * Label of attribute. Must unique and only contain lowercase letters and optional underscores
     * @type {string}
     * @memberof CreateAttributeRequestDTO
     */
    'label': string;
    /**
     * Name of attribute
     * @type {string}
     * @memberof CreateAttributeRequestDTO
     */
    'name': string;
    /**
     * Description of attribute
     * @type {string}
     * @memberof CreateAttributeRequestDTO
     */
    'description': string;
}

