/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProductCartDTO } from './product-cart-dto';

/**
 * 
 * @export
 * @interface CreateOrderRequestDTO
 */
export interface CreateOrderRequestDTO {
    /**
     * Index of address selected (index begin from 0)
     * @type {number}
     * @memberof CreateOrderRequestDTO
     */
    'addressSelected': number;
    /**
     * List of product selected
     * @type {Array<ProductCartDTO>}
     * @memberof CreateOrderRequestDTO
     */
    'productSelected': Array<ProductCartDTO>;
    /**
     * Payment method
     * @type {string}
     * @memberof CreateOrderRequestDTO
     */
    'paymentMethod': CreateOrderRequestDTOPaymentMethodEnum;
    /**
     * The return url after payment success
     * @type {string}
     * @memberof CreateOrderRequestDTO
     */
    'paymentReturnUrl'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateOrderRequestDTOPaymentMethodEnum {
    Cod = 'COD',
    Vnpay = 'VNPAY',
    Atm = 'ATM',
    Visa = 'VISA',
    Mastercard = 'MASTERCARD',
    Jcb = 'JCB'
}


