/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetStatsDataDTO } from './get-stats-data-dto';

/**
 * 
 * @export
 * @interface GetStatsResponseDTO
 */
export interface GetStatsResponseDTO {
    /**
     * From date to calculate revenue
     * @type {string}
     * @memberof GetStatsResponseDTO
     */
    'fromDate': string;
    /**
     * To date to calculate revenue, default is today
     * @type {string}
     * @memberof GetStatsResponseDTO
     */
    'toDate': string;
    /**
     * Total of orders in range of time
     * @type {number}
     * @memberof GetStatsResponseDTO
     */
    'totalOrders'?: number;
    /**
     * Total revenue in range of time
     * @type {number}
     * @memberof GetStatsResponseDTO
     */
    'totalRevenue'?: number;
    /**
     * Total of results
     * @type {number}
     * @memberof GetStatsResponseDTO
     */
    'totalResults'?: number;
    /**
     * Data of statistics
     * @type {Array<GetStatsDataDTO>}
     * @memberof GetStatsResponseDTO
     */
    'data'?: Array<GetStatsDataDTO>;
}

