/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetStatsDataDTO
 */
export interface GetStatsDataDTO {
    /**
     * total of orders in a period of time
     * @type {number}
     * @memberof GetStatsDataDTO
     */
    'orders'?: number;
    /**
     * total revenue in a period of time
     * @type {number}
     * @memberof GetStatsDataDTO
     */
    'revenue'?: number;
    /**
     * current stats date
     * @type {string}
     * @memberof GetStatsDataDTO
     */
    'date'?: string;
    /**
     * current stats date in string
     * @type {string}
     * @memberof GetStatsDataDTO
     */
    'dateString'?: string;
}

