/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CheckoutOrderSchemaDTO } from './checkout-order-schema-dto';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentOrderDTO } from './payment-order-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ProductsOrder } from './products-order';
// May contain unused imports in some cases
// @ts-ignore
import { ShippingOrderSchemaDTO } from './shipping-order-schema-dto';

/**
 * 
 * @export
 * @interface GetOrderByIdResponseDTO
 */
export interface GetOrderByIdResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof GetOrderByIdResponseDTO
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof GetOrderByIdResponseDTO
     */
    'userId': string;
    /**
     * 
     * @type {CheckoutOrderSchemaDTO}
     * @memberof GetOrderByIdResponseDTO
     */
    'checkoutOrder': CheckoutOrderSchemaDTO;
    /**
     * 
     * @type {ShippingOrderSchemaDTO}
     * @memberof GetOrderByIdResponseDTO
     */
    'shippingOrder': ShippingOrderSchemaDTO;
    /**
     * 
     * @type {PaymentOrderDTO}
     * @memberof GetOrderByIdResponseDTO
     */
    'paymentOrder'?: PaymentOrderDTO;
    /**
     * 
     * @type {string}
     * @memberof GetOrderByIdResponseDTO
     */
    'trackingCode': string;
    /**
     * 
     * @type {string}
     * @memberof GetOrderByIdResponseDTO
     */
    'orderStatus': GetOrderByIdResponseDTOOrderStatusEnum;
    /**
     * 
     * @type {Array<ProductsOrder>}
     * @memberof GetOrderByIdResponseDTO
     */
    'products': Array<ProductsOrder>;
}

/**
    * @export
    * @enum {string}
    */
export enum GetOrderByIdResponseDTOOrderStatusEnum {
    Pending = 'pending',
    Cancelled = 'cancelled',
    Processing = 'processing',
    Shipping = 'shipping',
    Completed = 'completed',
    Refunded = 'refunded'
}


