/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GhnWardDTO
 */
export interface GhnWardDTO {
    /**
     * Mã quận huyện
     * @type {number}
     * @memberof GhnWardDTO
     */
    'district_id': number;
    /**
     * Mã phường xã
     * @type {string}
     * @memberof GhnWardDTO
     */
    'ward_code': string;
    /**
     * Tên phường xã
     * @type {string}
     * @memberof GhnWardDTO
     */
    'ward_name': string;
    /**
     * Tên phường xã mở rộng
     * @type {Array<string>}
     * @memberof GhnWardDTO
     */
    'name_extension': Array<string>;
    /**
     * Loại hỗ trợ
     * @type {number}
     * @memberof GhnWardDTO
     */
    'support_type': GhnWardDTOSupportTypeEnum;
    /**
     * Có thể cập nhật COD
     * @type {boolean}
     * @memberof GhnWardDTO
     */
    'can_update_cod': boolean;
    /**
     * Trạng thái
     * @type {number}
     * @memberof GhnWardDTO
     */
    'status': GhnWardDTOStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum GhnWardDTOSupportTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
    * @export
    * @enum {string}
    */
export enum GhnWardDTOStatusEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


