/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GhnProvinceDTO
 */
export interface GhnProvinceDTO {
    /**
     * Mã tỉnh thành
     * @type {number}
     * @memberof GhnProvinceDTO
     */
    'province_id': number;
    /**
     * Tên tỉnh thành
     * @type {string}
     * @memberof GhnProvinceDTO
     */
    'province_name': string;
    /**
     * Mã quốc gia
     * @type {number}
     * @memberof GhnProvinceDTO
     */
    'country_id': number;
    /**
     * Tên tỉnh thành mở rộng
     * @type {Array<string>}
     * @memberof GhnProvinceDTO
     */
    'name_extension': Array<string>;
    /**
     * Trạng thái
     * @type {number}
     * @memberof GhnProvinceDTO
     */
    'status': GhnProvinceDTOStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum GhnProvinceDTOStatusEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


