/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KpiDTO
 */
export interface KpiDTO {
    /**
     * KPI id
     * @type {string}
     * @memberof KpiDTO
     */
    '_id': string;
    /**
     * KPI name
     * @type {string}
     * @memberof KpiDTO
     */
    'name': string;
    /**
     * KPI type
     * @type {string}
     * @memberof KpiDTO
     */
    'kpiType': KpiDTOKpiTypeEnum;
    /**
     * KPI value
     * @type {number}
     * @memberof KpiDTO
     */
    'value': number;
    /**
     * KPI start date
     * @type {string}
     * @memberof KpiDTO
     */
    'startDate': string;
    /**
     * KPI end date
     * @type {string}
     * @memberof KpiDTO
     */
    'endDate': string;
    /**
     * KPI status
     * @type {string}
     * @memberof KpiDTO
     */
    'kpiStatus'?: KpiDTOKpiStatusEnum;
    /**
     * KPI created date
     * @type {string}
     * @memberof KpiDTO
     */
    'createdAt'?: string;
    /**
     * KPI updated date
     * @type {string}
     * @memberof KpiDTO
     */
    'updatedAt'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum KpiDTOKpiTypeEnum {
    Revenue = 'revenue',
    OrderComplete = 'order_complete'
}
/**
    * @export
    * @enum {string}
    */
export enum KpiDTOKpiStatusEnum {
    Active = 'active',
    Inactive = 'inactive'
}


