/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderSchemaDTO } from './order-schema-dto';

/**
 * 
 * @export
 * @interface ListUserOrderResponseDTO
 */
export interface ListUserOrderResponseDTO {
    /**
     * Page number
     * @type {number}
     * @memberof ListUserOrderResponseDTO
     */
    'page': number;
    /**
     * Page size
     * @type {number}
     * @memberof ListUserOrderResponseDTO
     */
    'pageSize': number;
    /**
     * Total page with page size
     * @type {number}
     * @memberof ListUserOrderResponseDTO
     */
    'totalPage': number;
    /**
     * Total record with filter
     * @type {number}
     * @memberof ListUserOrderResponseDTO
     */
    'totalRecord': number;
    /**
     * List user orders
     * @type {Array<OrderSchemaDTO>}
     * @memberof ListUserOrderResponseDTO
     */
    'data': Array<OrderSchemaDTO>;
}

