/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NotificationsDTO } from './notifications-dto';

/**
 * 
 * @export
 * @interface ListNotificationsResponseDTO
 */
export interface ListNotificationsResponseDTO {
    /**
     * Page number
     * @type {number}
     * @memberof ListNotificationsResponseDTO
     */
    'page': number;
    /**
     * Page size
     * @type {number}
     * @memberof ListNotificationsResponseDTO
     */
    'pageSize': number;
    /**
     * Total page with page size
     * @type {number}
     * @memberof ListNotificationsResponseDTO
     */
    'totalPage': number;
    /**
     * Total record with filter
     * @type {number}
     * @memberof ListNotificationsResponseDTO
     */
    'totalRecord': number;
    /**
     * List of users
     * @type {Array<NotificationsDTO>}
     * @memberof ListNotificationsResponseDTO
     */
    'data': Array<NotificationsDTO>;
}

