/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginRequestDTO
 */
export interface LoginRequestDTO {
    /**
     * The email or userName of user to register
     * @type {string}
     * @memberof LoginRequestDTO
     */
    'emailOrUsername': string;
    /**
     * Password of user to register
     * @type {string}
     * @memberof LoginRequestDTO
     */
    'password': string;
}

