/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationsDTO
 */
export interface NotificationsDTO {
    /**
     * 
     * @type {string}
     * @memberof NotificationsDTO
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof NotificationsDTO
     */
    'notificationType': NotificationsDTONotificationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof NotificationsDTO
     */
    'recipientId'?: string;
    /**
     * The issuer of the notification
     * @type {string}
     * @memberof NotificationsDTO
     */
    'issuerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationsDTO
     */
    'content': string;
    /**
     * 
     * @type {object}
     * @memberof NotificationsDTO
     */
    'data'?: object;
    /**
     * The date when the notification is read, null if not read
     * @type {string}
     * @memberof NotificationsDTO
     */
    'readAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationsDTO
     */
    'canceledAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationsDTO
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationsDTO
     */
    'createdAt'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum NotificationsDTONotificationTypeEnum {
    NewProduct = 'newProduct',
    NewOrder = 'new-order',
    OrderStatusChanged = 'order-status-changed'
}


