/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CheckoutOrderSchemaDTO } from './checkout-order-schema-dto';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentOrderDTO } from './payment-order-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ProductOrderSchemaDTO } from './product-order-schema-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ShippingOrderSchemaDTO } from './shipping-order-schema-dto';

/**
 * 
 * @export
 * @interface OrderSchemaDTO
 */
export interface OrderSchemaDTO {
    /**
     * 
     * @type {string}
     * @memberof OrderSchemaDTO
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof OrderSchemaDTO
     */
    'userId': string;
    /**
     * 
     * @type {Array<ProductOrderSchemaDTO>}
     * @memberof OrderSchemaDTO
     */
    'products': Array<ProductOrderSchemaDTO>;
    /**
     * 
     * @type {CheckoutOrderSchemaDTO}
     * @memberof OrderSchemaDTO
     */
    'checkoutOrder': CheckoutOrderSchemaDTO;
    /**
     * 
     * @type {ShippingOrderSchemaDTO}
     * @memberof OrderSchemaDTO
     */
    'shippingOrder': ShippingOrderSchemaDTO;
    /**
     * 
     * @type {PaymentOrderDTO}
     * @memberof OrderSchemaDTO
     */
    'paymentOrder'?: PaymentOrderDTO;
    /**
     * 
     * @type {string}
     * @memberof OrderSchemaDTO
     */
    'trackingCode': string;
    /**
     * 
     * @type {string}
     * @memberof OrderSchemaDTO
     */
    'orderStatus': OrderSchemaDTOOrderStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum OrderSchemaDTOOrderStatusEnum {
    Pending = 'pending',
    Cancelled = 'cancelled',
    Processing = 'processing',
    Shipping = 'shipping',
    Completed = 'completed',
    Refunded = 'refunded'
}


