/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentOrderDTO
 */
export interface PaymentOrderDTO {
    /**
     * 
     * @type {string}
     * @memberof PaymentOrderDTO
     */
    'method': PaymentOrderDTOMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentOrderDTO
     */
    'status': PaymentOrderDTOStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentOrderDTO
     */
    'paymentUrl'?: string;
    /**
     * 
     * @type {object}
     * @memberof PaymentOrderDTO
     */
    'orderData'?: object;
}

/**
    * @export
    * @enum {string}
    */
export enum PaymentOrderDTOMethodEnum {
    Cod = 'COD',
    Vnpay = 'VNPAY',
    Atm = 'ATM',
    Visa = 'VISA',
    Mastercard = 'MASTERCARD',
    Jcb = 'JCB'
}
/**
    * @export
    * @enum {string}
    */
export enum PaymentOrderDTOStatusEnum {
    Pending = 'pending',
    Cancelled = 'cancelled',
    Processing = 'processing',
    WaitForPayment = 'wait_for_payment',
    Completed = 'completed',
    Refunded = 'refunded'
}


