/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductOrderSchemaDTO
 */
export interface ProductOrderSchemaDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductOrderSchemaDTO
     */
    'productId': string;
    /**
     * 
     * @type {number}
     * @memberof ProductOrderSchemaDTO
     */
    'quantity': number;
    /**
     * 
     * @type {string}
     * @memberof ProductOrderSchemaDTO
     */
    'sku': string;
    /**
     * 
     * @type {string}
     * @memberof ProductOrderSchemaDTO
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ProductOrderSchemaDTO
     */
    'updatedAt': string;
}

