/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProductAttributeDTO } from './product-attribute-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ProductImageDTO } from './product-image-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ProductVariationDTO } from './product-variation-dto';

/**
 * 
 * @export
 * @interface ProductDTO
 */
export interface ProductDTO {
    /**
     * ObjectId of product
     * @type {string}
     * @memberof ProductDTO
     */
    '_id': string;
    /**
     * Name of product
     * @type {string}
     * @memberof ProductDTO
     */
    'name': string;
    /**
     * Description of product
     * @type {string}
     * @memberof ProductDTO
     */
    'description': string;
    /**
     * ObjectId of category
     * @type {string}
     * @memberof ProductDTO
     */
    'category': string;
    /**
     * Status of product
     * @type {number}
     * @memberof ProductDTO
     */
    'status': ProductDTOStatusEnum;
    /**
     * 
     * @type {ProductAttributeDTO}
     * @memberof ProductDTO
     */
    'generalAttributes': ProductAttributeDTO;
    /**
     * General images of product
     * @type {Array<ProductImageDTO>}
     * @memberof ProductDTO
     */
    'generalImages': Array<ProductImageDTO>;
    /**
     * Description images of product
     * @type {Array<ProductImageDTO>}
     * @memberof ProductDTO
     */
    'descriptionImages': Array<ProductImageDTO>;
    /**
     * Variations of product
     * @type {Array<ProductVariationDTO>}
     * @memberof ProductDTO
     */
    'variations': Array<ProductVariationDTO>;
}

/**
    * @export
    * @enum {string}
    */
export enum ProductDTOStatusEnum {
    NUMBER_MINUS_1 = -1,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8
}


