/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductCartSchemaDTO
 */
export interface ProductCartSchemaDTO {
    /**
     * Product ID
     * @type {string}
     * @memberof ProductCartSchemaDTO
     */
    'productId': string;
    /**
     * Product SKU
     * @type {string}
     * @memberof ProductCartSchemaDTO
     */
    'sku': string;
    /**
     * Product quantity
     * @type {number}
     * @memberof ProductCartSchemaDTO
     */
    'quantity': number;
    /**
     * Product created at
     * @type {string}
     * @memberof ProductCartSchemaDTO
     */
    'createdAt': string;
    /**
     * Product updated at
     * @type {string}
     * @memberof ProductCartSchemaDTO
     */
    'updatedAt': string;
}

