/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductCartDTO
 */
export interface ProductCartDTO {
    /**
     * 
     * @type {object}
     * @memberof ProductCartDTO
     */
    'productId': object;
    /**
     * Product SKU
     * @type {string}
     * @memberof ProductCartDTO
     */
    'sku': string;
    /**
     * Product quantity
     * @type {number}
     * @memberof ProductCartDTO
     */
    'quantity': number;
}

