/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductAttributeDTO
 */
export interface ProductAttributeDTO {
    /**
     * Key of the attribute
     * @type {string}
     * @memberof ProductAttributeDTO
     */
    'k': string;
    /**
     * Value of the attribute
     * @type {string}
     * @memberof ProductAttributeDTO
     */
    'v': string;
    /**
     * Unit of the attribute
     * @type {string}
     * @memberof ProductAttributeDTO
     */
    'u'?: string;
}

