/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProductAttributeDTO } from './product-attribute-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ProductImageDTO } from './product-image-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ProductPriceDTO } from './product-price-dto';

/**
 * 
 * @export
 * @interface ProductVariationDTO
 */
export interface ProductVariationDTO {
    /**
     * The unique sku of product variation
     * @type {string}
     * @memberof ProductVariationDTO
     */
    'sku': string;
    /**
     * Attributes of product\'s variations
     * @type {Array<ProductAttributeDTO>}
     * @memberof ProductVariationDTO
     */
    'attributes': Array<ProductAttributeDTO>;
    /**
     * 
     * @type {ProductPriceDTO}
     * @memberof ProductVariationDTO
     */
    'price': ProductPriceDTO;
    /**
     * Number of stock
     * @type {number}
     * @memberof ProductVariationDTO
     */
    'stock': number;
    /**
     * Image of product\'s variations
     * @type {Array<ProductImageDTO>}
     * @memberof ProductVariationDTO
     */
    'images': Array<ProductImageDTO>;
    /**
     * Status of product
     * @type {number}
     * @memberof ProductVariationDTO
     */
    'status': ProductVariationDTOStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ProductVariationDTOStatusEnum {
    NUMBER_MINUS_1 = -1,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8
}


