/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserRequestDTO
 */
export interface UpdateUserRequestDTO {
    /**
     * Username of user
     * @type {string}
     * @memberof UpdateUserRequestDTO
     */
    'userName'?: string;
    /**
     * First name of user
     * @type {string}
     * @memberof UpdateUserRequestDTO
     */
    'firstName'?: string;
    /**
     * Last name of user
     * @type {string}
     * @memberof UpdateUserRequestDTO
     */
    'lastName'?: string;
    /**
     * PublicId of user\'s avatar
     * @type {string}
     * @memberof UpdateUserRequestDTO
     */
    'avatarPublicId'?: string;
}

