/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateKpiRequestDTO
 */
export interface UpdateKpiRequestDTO {
    /**
     * KPI name
     * @type {string}
     * @memberof UpdateKpiRequestDTO
     */
    'name'?: string;
    /**
     * KPI value
     * @type {number}
     * @memberof UpdateKpiRequestDTO
     */
    'value'?: number;
    /**
     * KPI start date
     * @type {string}
     * @memberof UpdateKpiRequestDTO
     */
    'startDate'?: string;
    /**
     * KPI end date
     * @type {string}
     * @memberof UpdateKpiRequestDTO
     */
    'endDate'?: string;
    /**
     * KPI status
     * @type {string}
     * @memberof UpdateKpiRequestDTO
     */
    'kpiStatus'?: UpdateKpiRequestDTOKpiStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateKpiRequestDTOKpiStatusEnum {
    Active = 'active',
    Inactive = 'inactive'
}


