/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddressSchemaDTO } from './address-schema-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ImageSchemaDTO } from './image-schema-dto';

/**
 * 
 * @export
 * @interface UserDataResponseDTO
 */
export interface UserDataResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof UserDataResponseDTO
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof UserDataResponseDTO
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserDataResponseDTO
     */
    'userName': string;
    /**
     * 
     * @type {string}
     * @memberof UserDataResponseDTO
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof UserDataResponseDTO
     */
    'lastName': string;
    /**
     * 
     * @type {Array<AddressSchemaDTO>}
     * @memberof UserDataResponseDTO
     */
    'address': Array<AddressSchemaDTO>;
    /**
     * 
     * @type {string}
     * @memberof UserDataResponseDTO
     */
    'role': UserDataResponseDTORoleEnum;
    /**
     * 
     * @type {ImageSchemaDTO}
     * @memberof UserDataResponseDTO
     */
    'avatar'?: ImageSchemaDTO;
    /**
     * 
     * @type {string}
     * @memberof UserDataResponseDTO
     */
    'accessToken': string;
    /**
     * 
     * @type {string}
     * @memberof UserDataResponseDTO
     */
    'refreshToken': string;
}

/**
    * @export
    * @enum {string}
    */
export enum UserDataResponseDTORoleEnum {
    Manager = 'Manager',
    Staff = 'Staff',
    User = 'User'
}


