/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddressSchemaDTO } from './address-schema-dto';
// May contain unused imports in some cases
// @ts-ignore
import { BlockSchemaDTO } from './block-schema-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ImageSchemaDTO } from './image-schema-dto';

/**
 * 
 * @export
 * @interface UserMntResponseDTO
 */
export interface UserMntResponseDTO {
    /**
     * The user id
     * @type {string}
     * @memberof UserMntResponseDTO
     */
    '_id': string;
    /**
     * The user email
     * @type {string}
     * @memberof UserMntResponseDTO
     */
    'email': string;
    /**
     * The user username
     * @type {string}
     * @memberof UserMntResponseDTO
     */
    'userName': string;
    /**
     * Whether the user email is verified or not
     * @type {boolean}
     * @memberof UserMntResponseDTO
     */
    'emailVerified': boolean;
    /**
     * The user role
     * @type {string}
     * @memberof UserMntResponseDTO
     */
    'role': string;
    /**
     * 
     * @type {ImageSchemaDTO}
     * @memberof UserMntResponseDTO
     */
    'avatar'?: ImageSchemaDTO;
    /**
     * The user address
     * @type {Array<AddressSchemaDTO>}
     * @memberof UserMntResponseDTO
     */
    'address': Array<AddressSchemaDTO>;
    /**
     * The user first name
     * @type {string}
     * @memberof UserMntResponseDTO
     */
    'firstName': string;
    /**
     * The user last name
     * @type {string}
     * @memberof UserMntResponseDTO
     */
    'lastName': string;
    /**
     * 
     * @type {BlockSchemaDTO}
     * @memberof UserMntResponseDTO
     */
    'block': BlockSchemaDTO;
    /**
     * The user created date
     * @type {string}
     * @memberof UserMntResponseDTO
     */
    'createdAt': string;
    /**
     * The user updated date
     * @type {string}
     * @memberof UserMntResponseDTO
     */
    'updatedAt': string;
}

