/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttributeDTO } from './attribute-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ImageRequestDTO } from './image-request-dto';
// May contain unused imports in some cases
// @ts-ignore
import { PriceDTO } from './price-dto';

/**
 * 
 * @export
 * @interface VariationRequestDTO
 */
export interface VariationRequestDTO {
    /**
     * Attributes of product
     * @type {Array<AttributeDTO>}
     * @memberof VariationRequestDTO
     */
    'attributes': Array<AttributeDTO>;
    /**
     * Stock of product
     * @type {number}
     * @memberof VariationRequestDTO
     */
    'stock': number;
    /**
     * 
     * @type {PriceDTO}
     * @memberof VariationRequestDTO
     */
    'price': PriceDTO;
    /**
     * Status of product (number)
     * @type {string}
     * @memberof VariationRequestDTO
     */
    'status'?: VariationRequestDTOStatusEnum;
    /**
     * Images of product
     * @type {Array<ImageRequestDTO>}
     * @memberof VariationRequestDTO
     */
    'images'?: Array<ImageRequestDTO>;
}

/**
    * @export
    * @enum {string}
    */
export enum VariationRequestDTOStatusEnum {
    _1ComingSoon = '1: ComingSoon',
    _2NewArrival = '2: NewArrival',
    _3PreOrder = '3: Pre_order',
    _4OnSales = '4: OnSales',
    _5Hide = '5: Hide',
    _6NotSales = '6: NotSales',
    _7LowStock = '7: LowStock',
    _8TemporarilyOutOfStock = '8: TemporarilyOutOfStock',
    Deleted1 = 'Deleted: -1',
    _1Deleted = '-1: Deleted',
    ComingSoon1 = 'ComingSoon: 1',
    NewArrival2 = 'NewArrival: 2',
    PreOrder3 = 'Pre_order: 3',
    OnSales4 = 'OnSales: 4',
    Hide5 = 'Hide: 5',
    NotSales6 = 'NotSales: 6',
    LowStock7 = 'LowStock: 7',
    TemporarilyOutOfStock8 = 'TemporarilyOutOfStock: 8'
}


