/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * This is the documentation for the TechCell RESTful API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VerifyForgotPasswordDTO
 */
export interface VerifyForgotPasswordDTO {
    /**
     * Email of the user
     * @type {string}
     * @memberof VerifyForgotPasswordDTO
     */
    'email': string;
    /**
     * OTP code sent to the user
     * @type {string}
     * @memberof VerifyForgotPasswordDTO
     */
    'otpCode': string;
    /**
     * Password of the user
     * @type {string}
     * @memberof VerifyForgotPasswordDTO
     */
    'password': string;
    /**
     * Re-enter password of the user
     * @type {string}
     * @memberof VerifyForgotPasswordDTO
     */
    're_password': string;
}

